services:
  server:
    restart: unless-stopped
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  client:
    restart: unless-stopped
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - server
